# Generated by Django 4.0.3 on 2022-04-06 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begins_at', models.DateTimeField(default=datetime.datetime(2022, 4, 6, 13, 12, 3, 271080))),
                ('ends_at', models.DateTimeField(default=datetime.datetime(2022, 4, 6, 13, 12, 3, 271080))),
                ('cost', models.DecimalField(decimal_places=4, default=50.0, max_digits=10)),
                ('comment', models.TextField(max_length=250)),
                ('canceled', models.BooleanField(default=False)),
                ('payed', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('lastname', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FoodBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('is_active', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.TextField(max_length=4)),
                ('species', models.TextField(max_length=20)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default="Pudling Pet's Room", max_length=50)),
                ('reserved', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.TextField(max_length=4)),
                ('species', models.TextField(max_length=20)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('room_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.roomtype'),
        ),
        migrations.CreateModel(
            name='FoodBrandBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('food_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.foodbrand')),
            ],
        ),
        migrations.AddField(
            model_name='foodbrand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.foodtype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to='booking.client'),
        ),
    ]
