# Generated by Django 4.0.3 on 2022-04-06 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='begins_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 13, 43, 29, 595413)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ends_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 13, 43, 29, 596413)),
        ),
    ]
