# Generated by Django 4.0.3 on 2022-04-06 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_begins_at_alter_booking_ends_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='begins_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 13, 45, 0, 919947)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ends_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 13, 45, 0, 919947)),
        ),
    ]
