# Generated by Django 4.0.3 on 2022-04-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_begins_at_alter_booking_ends_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='begins_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ends_at',
            field=models.DateTimeField(),
        ),
    ]
