# Generated by Django 4.0.3 on 2022-04-07 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_begins_at_alter_booking_ends_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtype',
            old_name='species',
            new_name='accepted_species',
        ),
        migrations.RenameField(
            model_name='roomtype',
            old_name='species',
            new_name='accepted_species',
        ),
        migrations.RemoveField(
            model_name='foodbrand',
            name='category',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='size',
        ),
        migrations.RemoveField(
            model_name='room',
            name='category',
        ),
        migrations.AddField(
            model_name='foodtype',
            name='food_brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='booking.foodbrand'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='booking.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='foodbrand',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
